<div class="well">
    <a class="btn primary" href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'create'));?>"><?php echo $this->translate('addAction'); ?></a>
</div>

<?php if(!empty($this->category)) : ?>
<table class="table table-bordered table-striped table-condensed">
    <thead>
       <tr>
           <th><?php echo $this->translate('transactionCategoryName'); ?></th>
           <th>&nbsp;</th>
       </tr>
    </thead>
    <tbody>
<?php foreach ($this->category as $category) : ?>
    <tr>
        <td>
            <?php echo $category->getName(); ?>
            <?php foreach ($category->getChildren() as $child) : ?>
                <br /><?php echo $child->getName(); ?>
            <?php endforeach; ?>
        </td>
        <td>
            <ul class="actions clearfix">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'update', 'id' => $category->getId()));?>"><?php echo $this->translate('editAction'); ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'delete', 'id' => $category->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a>
                </li>
            </ul>
            <?php foreach ($category->getChildren() as $child) : ?>
                <br />
                <ul class="actions clearfix">
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'update', 'id' => $child->getId()));?>"><?php echo $this->translate('editAction'); ?></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'delete', 'id' => $child->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a>
                    </li>
                </ul>
            <?php endforeach; ?>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
