<h2><?php echo $this->title; ?></h2>

<p><a class="button small" href="<?php echo $this->url(array('controller' => 'payee', 'action' => 'create'));?>"><?php echo $this->translate('addAction'); ?></a></p>

<?php if(!empty($this->payees)) : ?>
<table class="defaultTable">
    <thead>
        <tr>
            <th><?php echo $this->translate('payeeName'); ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->payees as $payee) : ?>
    <tr>
        <td><?php echo $payee->getName(); ?></td>
        <td>
            <ul class="actions clearfix">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'payee', 'action' => 'update', 'id' => $payee->getId()));?>"><?php echo $this->translate('editAction'); ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'payee', 'action' => 'delete', 'id' => $payee->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a>
                </li>
            </ul>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
