<?php $this->layout()->variation = 'variation/sidebar'; ?>

<?php $this->placeholder('quickAction')->captureStart(); ?>
    <a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'create'));?>"><i class="icon-plus"></i><?php echo $this->translate('addAction'); ?></a>
<?php $this->placeholder('quickAction')->captureEnd(); ?>

<?php $this->placeholder('sidebar')->captureStart(); ?>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'list'));?>"><?php echo $this->translate('transactionTitle'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'list'));?>"><?php echo $this->translate('scheduledTransactionTitle'); ?></a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'list'));?>"><?php echo $this->translate('transactionCategoryTitle'); ?></a></li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd(); ?>

<table id="scheduledTransactionsTable" class="table table-bordered table-striped">
    <thead>
       <tr>
           <th><?php echo $this->translate('scheduledTransactionNextDate'); ?></th>
           <th><?php echo $this->translate('scheduledTransactionFrequency'); ?></th>
           <th><?php echo $this->translate('transactionType'); ?></th>
           <th><?php echo $this->translate('transactionCategory'); ?></th>
           <th><?php echo $this->translate('transactionAmount'); ?></th>
           <th><?php echo $this->translate('scheduledTransactionActive'); ?></th>
           <th>&nbsp;</th>
       </tr>
    </thead>
    <tbody>
    </tbody>
</table>
