<?php $this->layout()->variation = 'variation/sidebar'; ?>

<?php $this->placeholder('quickAction')->captureStart(); ?>
    <a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'create'));?>"><i class="icon-plus"></i><?php echo $this->translate('addAction'); ?></a>
<?php $this->placeholder('quickAction')->captureEnd(); ?>

<?php $this->placeholder('sidebar')->captureStart(); ?>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'list'));?>"><?php echo $this->translate('transactionTitle'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'list'));?>"><?php echo $this->translate('scheduledTransactionTitle'); ?></a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'list'));?>"><?php echo $this->translate('transactionCategoryTitle'); ?></a></li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd(); ?>

<?php if(!empty($this->transactions)) : ?>
<table class="table table-bordered table-striped">
    <thead>
       <tr>
           <th><?php echo $this->translate('scheduledTransactionNextDate'); ?></th>
           <th><?php echo $this->translate('scheduledTransactionFrequency'); ?></th>
           <th><?php echo $this->translate('transactionType'); ?></th>
           <th><?php echo $this->translate('transactionCategory'); ?></th>
           <th><?php echo $this->translate('transactionAmount'); ?></th>
           <th><?php echo $this->translate('scheduledTransactionActive'); ?></th>
           <th>&nbsp;</th>
       </tr>
    </thead>
    <tbody>
<?php foreach ($this->transactions as $transaction) : ?>
    <tr>
        <td><?php echo $transaction->getNextDate()->format('Y-m-d'); ?></td>
        <td><?php echo $transaction->getFrequency(); ?></td>
        <td><?php echo $this->translate($transaction->getType()->getTag()); ?></td>
        <td><?php echo $transaction->getCategory()->getName(); ?></td>
        <td><?php echo $this->currency($transaction->getAmount()); ?></td>
        <td><?php echo $transaction->isActive(); ?></td>
        <td>
            <ul class="actions clearfix">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'update', 'id' => $transaction->getId()));?>"><?php echo $this->translate('editAction'); ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'delete', 'id' => $transaction->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a>
                </li>
            </ul>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
