<?php $this->layout()->variation = 'variation/sidebar'; ?>

<?php $this->placeholder('sidebar')->captureStart(); ?>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'list'));?>"><?php echo $this->translate('transactionTitle'); ?></a></li>
    <li class="active"><a href="<?php echo $this->url(array('controller' => 'scheduled-transaction', 'action' => 'list'));?>"><?php echo $this->translate('scheduledTransactionTitle'); ?></a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'transaction-category', 'action' => 'list'));?>"><?php echo $this->translate('transactionCategoryTitle'); ?></a></li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd(); ?>

<?php echo $this->form; ?>
