<h2><?php echo $this->title; ?></h2>

<a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'add'));?>"><?php echo $this->translate('addAction'); ?></a><br />

<?php if(!empty($this->accounts)) : ?>
<table cellspacing="0">
<?php foreach ($this->accounts as $account) : ?>
    <tr>
        <td><?php echo $account->getName(); ?></td>
        <td><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'edit', 'id' => $account->getId()));?>"><?php echo $this->translate('editAction'); ?></a></td>
        <td><a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'delete', 'id' => $account->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
