<?php $this->placeholder('quickAction')->captureStart(); ?>
    <a href="<?php echo $this->url(array('controller' => 'bank', 'action' => 'create'));?>"><i class="icon-plus"></i><?php echo $this->translate('addAction'); ?></a>
<?php $this->placeholder('quickAction')->captureEnd(); ?>

<?php if(!empty($this->banks)) : ?>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th><?php echo $this->translate('bankName'); ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->banks as $bank) : ?>
    <tr>
        <td><?php echo $bank->getName(); ?></td>
        <td>
            <ul class="actions clearfix">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'bank', 'action' => 'update', 'id' => $bank->getId()));?>"><?php echo $this->translate('editAction'); ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'bank', 'action' => 'delete', 'id' => $bank->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a>
                </li>
            </ul>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
