<div class="topbar">
    <div class="fill">
        <div class="container">
            <a class="brand" href="<?php echo $this->url(array('controller' => 'dashboard', 'action' => 'index')); ?>">financeapp</a>
            <ul>
                <li <?php echo ($this->isActive('dashboard') ? 'class="active"' : ''); ?>>
                <a href="<?php echo $this->url(array('controller' => 'dashboard', 'action' => 'index'));?>">
                    <?php echo $this->translate('dashboardLinkTitle'); ?></a></li>
                <li <?php echo ($this->isActive('transaction') ? 'class="active"' : ''); ?>>
                <a href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'index'));?>">
                    <?php echo $this->translate('transactionLinkTitle'); ?></a></li>
                <li <?php echo ($this->isActive('account') ? 'class="active"' : ''); ?>>
                <a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'index'));?>">
                    <?php echo $this->translate('accountLinkTitle'); ?></a></li>
                <li <?php echo ($this->isActive('bank') ? 'class="active"' : ''); ?>>
                <a href="<?php echo $this->url(array('controller' => 'bank', 'action' => 'index'));?>">
                    <?php echo $this->translate('bankLinkTitle'); ?></a></li>
                <li <?php echo ($this->isActive('payee') ? 'class="active"' : ''); ?>>
                <a href="<?php echo $this->url(array('controller' => 'payee', 'action' => 'index'));?>">
                    <?php echo $this->translate('payeeLinkTitle'); ?></a></li>
            </ul>
            <ul class="nav secondary-nav">
                <li><a href="<?php echo $this->url(array('controller' => 'setting', 'action' => 'index'));?>">
                    <?php echo $this->translate('settingsLinkTitle'); ?></a></li>
            </ul>
        </div>
    </div>
</div>