<?php echo $this->partial('_navigation.phtml'); ?>
<div class="container-fluid">
    <div id="wrapper">
        <div class="row-fluid">
            <div class="span12">
                <div class="page-header">
                    <h1><?php echo $this->pageTitle; ?></h1>
                    <?php echo $this->placeholder('quickAction')
                        ->setPrefix("<div id=\"quickAction\">\n")
                        ->setPostFix("</div>\n"); ?>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <?php if($this->layout()->variation): ?>
                <?php $this->layout()->setLayout($this->layout()->variation); ?>
                <?php echo $this->layout()->render(); ?>
            <?php else: ?>
                <?php echo $this->layout()->content; ?>
            <?php endif; ?>
        </div>
    </div>
    <hr />
    <footer>
       <p>Copyright &copy; 2011 financeapp</p>
    </footer>
</div>