<?php echo $this->doctype() . PHP_EOL; ?>
<html>
    <head>
        <?php echo $this->headMeta() . PHP_EOL; ?>
        <?php $this->headTitle()->setSeparator(' - ') . PHP_EOL; ?>
        <?php echo $this->headTitle() . PHP_EOL; ?>
        <?php echo $this->headLink() . PHP_EOL; ?>
        <?php echo $this->headStyle() . PHP_EOL; ?>
        <?php
            echo $this->jQuery()
                ->setRenderMode(ZendX_JQuery::RENDER_STYLESHEETS) . PHP_EOL;
        ?>
    </head>
    <body>
        <?php // NESTED LAYOUT SUPPORT ?>
        <?php if ($this->layout()->nestedLayout): ?>
            <?php $this->layout()->setLayout($this->layout()->nestedLayout); ?>
            <?php echo $this->layout()->render(); ?>
        <?php else: ?>
            <?php echo $this->layout()->content; ?>
        <?php endif; ?>
        <?php
            echo $this->jQuery()->setRenderMode(
                ZendX_JQuery::RENDER_LIBRARY
                | ZendX_JQuery::RENDER_JAVASCRIPT
                | ZendX_JQuery::RENDER_JQUERY_ON_LOAD
            ) . PHP_EOL;
        ?>
        <?php echo $this->headScript() . PHP_EOL; ?>
        <?php echo $this->inlineScript() . PHP_EOL; ?>
    </body>
    <!-- Zend Framework <?php echo Zend_Version::VERSION; ?>, Doctrine: Common <?php echo Doctrine\Common\Version::VERSION; ?>, DBAL <?php echo Doctrine\DBAL\Version::VERSION; ?>, ORM <?php echo Doctrine\ORM\Version::VERSION; ?> -->
</html>
