<h2><?php echo $this->title; ?></h2>

<p><a class="button small" href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'add'));?>"><?php echo $this->translate('addAction'); ?></a></p>

<?php if(!empty($this->transactions)) : ?>
<table cellspacing="0" class="defaultTable">
    <thead>
       <tr>
           <th><?php echo $this->translate('transactionAmount'); ?></th>
           <th>&nbsp;</th>
       </tr>
    </thead>
    <tbody>
<?php foreach ($this->transactions as $transaction) : ?>
    <tr>
        <td><?php echo $transaction->getAmount(); ?></td>
        <td>
            <ul class="actions clearfix">
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'edit', 'id' => $transaction->getId()));?>"><?php echo $this->translate('editAction'); ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url(array('controller' => 'transaction', 'action' => 'delete', 'id' => $transaction->getId()));?>"><?php echo $this->translate('deleteAction'); ?></a>
                </li>
            </ul>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
